version: "3.9"


services:
  pg_db:
    image: postgres:13.3
    restart: always
    environment:
      POSTGRES_DB: "postgres"
      POSTGRES_USER: "postgres"
      POSTGRES_PASSWORD: "1478"
    ports:
      - "5432:5432"



  games:
    container_name: da-games
    build:
      context: .
      dockerfile: Dockerfile
    network_mode: host
    depends_on:
      - pg_db
    ports:
      - "3000:8000"

